-- AlterTable
ALTER TABLE "User" ADD COLUMN "reportDigestFrequency" TEXT NOT NULL DEFAULT 'NEVER';
ALTER TABLE "User" ADD COLUMN "reportDigestReportsCsv" TEXT NOT NULL DEFAULT 'COURSE_POPULARITY,TIME_CROWDING,TRAINER_PERFORMANCE';
ALTER TABLE "User" ADD COLUMN "reportDigestLastSentAt" DATETIME;
